- name: set hostname {{ hostname }}
  hostname: name={{ hostname }}

- name: reboot after change hostname
  shell: sleep 2s && /sbin/reboot &

- name: wait for the server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=20
