language: python
python:
  - "2.7"
install:
  - pip install ansible
before_script:
  - pushd ~/build/volanja
  - git clone https://github.com/willthames/ansible-lint.git
  - export PYTHONPATH=$PYTHONPATH:`pwd`/ansible-lint/lib
  - export PATH=$PATH:`pwd`/ansible-lint/bin
script:
  - popd
  - ansible-lint site.yml
