- name: Install_Redmine
  hosts: localhost
  user: root
  roles:
    #for root
    #- hostname
    - Packages
    - user
    #for redmine
    #- ruby
    - postgresql
    #- mariadb
    - redmine
    - redmine-plugins
  vars:
    db: postgresql
    #db: mariadb
    hostname: cadence
    redmine_home: /home/redmine
    redmine_version: 3.3.3
