- name: Install_Redmine
  hosts: server
  user: root
  roles:
    #for root
    - hostname
    - Packages
    - user
    #for redmine
    - ruby
    - postgresql
    #- mariadb
    - redmine
    - redmine-plugins
  vars:
    db: postgresql
    #db: mariadb
