---
# PostgreSQL
- name: Install pgdg
  yum: name={{ item }} state=present
  with_items:
    - http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm

- name: Install PostgreSQL
  yum: name={{ item }} state=present enablerepo=pgdg94
  with_items:
    - postgresql94-server
